### ISSUE TITLE
How to enable ITF Code (Interleaved Two of Five) in Windev Mobile 25 ?

### ISSUE THREAD

**Issue by reuniware** [ltrudu/WindevMobileDataWedgeWrapper#1]
Hello.

I would like to know how to programmatically enable ITF Code barcode scanning in Windev Mobile 25 ?
DataWedge version is 6.7.

An alternative would be to show the Settings page as done in DWDemo app in TC25...

When I modify the profile of my application from the app DataWedge, this is not taken into account...
But when I modify the settings in DWDemo then it is ok (ITF scanning is ok after enabling it)...

Thanks.

**Comment by reuniware** [comment]
Solution 👍 
ZebraDWEnregistrerCallbackDeScan("FEN_SaisieModeDirect.CB_TraiteScan", "COL_MyCompanyScan.CB_EnregistrerCallbackSucces", "COL_MyCompanyScan.CB_EnregistrerCallbackErreur")

clSettings est un CZebraDWConfigurationDuProfil
clSettings.m_sProfileName															= "DWDemo"
clSettings.m_nTimeOutMS																= 5000
clSettings.m_clScannerPlugin.m_clDecoders.m_bdecoder_i2of5							= Vrai
clSettings.m_clScannerPlugin.m_clDecodersParams.m_bdecoder_d2of5_redundancy			= Vrai
clSettings.m_clScannerPlugin.m_clDecodersParams.m_bdecoder_i2of5_redundancy			= Vrai
clSettings.m_clScannerPlugin.m_clDecodersParams.m_bdecoder_matrix_2of5_redundancy	= Vrai
clSettings.m_clScannerPlugin.m_clDecodersParams.m_edecoder_i2of5_security_level		= CZebraDWProfilePluginScannerDecodersParams.SECURITY_LEVEL_0
clSettings.m_clScannerPlugin.m_clDecodersParams.m_ndecoder_d2of5_length1			= 6
clSettings.m_clScannerPlugin.m_clDecodersParams.m_ndecoder_d2of5_length2			= 55
clSettings.m_clScannerPlugin.m_clDecodersParams.m_ndecoder_i2of5_length1			= 6
clSettings.m_clScannerPlugin.m_clDecodersParams.m_ndecoder_i2of5_length2			= 55

ZebraDWInitialiserUnProfil(clSettings, "COL_MyCompanyScan.CB_ProfilInitialisé", "COL_MyCompanyScan.CB_Erreur2")

**Comment by ltrudu** [comment]
Hi,
Sorry for seeing the issue a little bit late : 13 days..., I did not seee the email since it originated from "Quant & Fintech Opensource Projects" directly and not "Github"... 

💯Happy that you found the solution 💯

**Comment by reuniware** [comment]
Salut! Merci pour ta réponse.
Oui j'ai pu trouver une solution, après avoir un peu galéré, mais j'aime bien les challenges 👍
