### ISSUE TITLE
Absence de bip de confirmation sur Zebra TC21

### ISSUE THREAD

**Issue by jturazzi** [ltrudu/WindevMobileDataWedgeWrapper#3]
Bonjour Laurent,

Lors de l'utilisation du Zebra TC21 avec WindevMobileDataWedgeWrapper, le bip de confirmation après un scan n'est pas audible. Cependant, le scan fonctionne correctement.

Ce problème apparaît :

Sur mon projet d'entreprise.
Avec le code d'exemple Zebra Scan inclus dans WinDev Mobile.
En revanche, le bip fonctionne parfaitement avec l'application DWDemo sur un modèle TC21.

![Stack](https://github.com/user-attachments/assets/7fefa535-f865-4189-97f0-1ecf2188a9f1)

Je testerai prochainement sur un modèle TC22 pour vérifier si le problème persiste.

Merci d'avance pour ton aide !

Cordialement,

**Comment by jturazzi** [comment]
Cela peut être lié sinon au DataWedgeIntentWrapper.

**Comment by ltrudu** [comment]
Bonjour,
Je dois effectuer quelques tests sur DataWedge la semaine prochaine, je reviens vers vous avec de plus amples informations.
Bien cordialement,
Laurent

**Comment by jturazzi** [comment]
Merci @ltrudu !

**Comment by ltrudu** [comment]
Bonjour,
Mea culpa, l'erreur vient de la valeur que j'ai mis par défaut au membre m_sdecode_audio_feedback_uri de la classe WindevMobile CZebraDWProfilePluginScannerScanParams.
J'ai remonté le problème à PCSoft.
Pour corriger le problème, ouvrez le composant intene ScannerDataWedge.
Dans la classe CZebraDWProfilePluginScannerScanParams, remplacez la ligne 4:
	m_sdecode_audio_feedback_uri is string = "content://media/external/audio/media/null", Serialize = "decode_audio_feedback_uri"
Par la ligne suivante:
	m_sdecode_audio_feedback_uri is string = Null, Serialize = "decode_audio_feedback_uri"
Une fois la valeur mise à Null, la librairie utilisera le Beep par défaut.

**Comment by ltrudu** [comment]
Fermé suite à correction

**Comment by jturazzi** [comment]
Merci beaucoup @ltrudu je test le correctif demain.

**Comment by jturazzi** [comment]
Bonjour @ltrudu le changement a bien solutionné le problème. Merci encore.
